#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use libnv_sys::nvlist_t;

// These are defined as macros, so can't be autogenerated with bindgen.
pub const CASPER_SERVICE_STDIO: u64 = 0x1;
pub const CASPER_SERVICE_FD: u64 = 0x2;
pub const CASPER_SERVICE_NO_UNIQ_LIMITS: u64 = 0x4;

include!("ffi.rs");
