setup: &SETUP
  env:
    HOME: /tmp # cargo needs it
    RUSTFLAGS: -D warnings
    VERSION: nightly
  setup_script:
    - pkg install -y llvm
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal
    - $HOME/.cargo/bin/rustup toolchain install $VERSION

task:
  env:
    HOME: /tmp  # cargo cache needs it
    TARGET: x86_64-unknown-freebsd
    VERSION: nightly
  matrix:
    - name: FreeBSD 13 amd64 nightly
      freebsd_instance:
        image: freebsd-13-2-release-amd64
    - name: FreeBSD 14 amd64 nightly
      freebsd_instance:
        image: freebsd-14-0-release-amd64-ufs
    - name: FreeBSD 14 amd64 stable
      env:
        VERSION: 1.77.0
      freebsd_instance:
        image: freebsd-14-0-release-amd64-ufs
    - name: FreeBSD 14 i686 nightly
      # Test i686 FreeBSD in 32-bit emulation on a 64-bit host.
      env:
        TARGET: i686-unknown-freebsd
      freebsd_instance:
        image: freebsd-14-0-release-amd64-ufs
  << : *SETUP
  extra_setup_script:
    - . $HOME/.cargo/env
    - if [ "$TARGET" = "i686-unknown-freebsd" ]; then rustup target add --toolchain $VERSION i686-unknown-freebsd; fi
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  test_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION test --target $TARGET
  casper_test_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION test --target $TARGET --all-features
    - cargo +$VERSION run --all-features --example getuid
  doc_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION doc --target $TARGET --no-deps --all-features
  before_cache_script: rm -rf $HOME/.cargo/registry/index 

# Stuff that doesn't need to be repeated for each target, env, and toolchain
lint_task:
  name: lint
  env:
    HOME: /tmp  # cargo cache needs it
    VERSION: nightly
  freebsd_instance:
    image: freebsd-14-0-release-amd64-ufs
  << : *SETUP
  extra_setup_script:
    - . $HOME/.cargo/env
    - rustup component add --toolchain $VERSION clippy
    - rustup component add --toolchain $VERSION rustfmt
  cargo_cache:
    folder: $HOME/.cargo/registry
  clippy_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION clippy --all-targets -- -D warnings
    - cargo +$VERSION clippy --all-targets --all-features -- -D warnings
  fmt_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION fmt --all -- --check --color=never
  audit_script:
    - . $HOME/.cargo/env
    - cargo install --version=0.17.6 cargo-audit
    - cargo audit
  before_cache_script: rm -rf $CARGO_HOME/registry/index
