setup: &SETUP
  env:
    HOME: /tmp # cargo needs it
    RUSTFLAGS: -D warnings
  setup_script:
    - pkg install -y llvm
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain $VERSION

test: &TEST
  test_script:
    - . $HOME/.cargo/env
    - cargo test --target $TARGET
  casper_test_script:
    - . $HOME/.cargo/env
    - cargo test --target $TARGET --all-features
    - cargo run --all-features --example getuid
  doc_script:
    - . $HOME/.cargo/env
    - cargo doc --target $TARGET --no-deps --all-features

task:
  env:
    HOME: /tmp  # cargo cache needs it
    TARGET: x86_64-unknown-freebsd
    VERSION: 1.81.0
  matrix:
    - name: FreeBSD 14 amd64 stable
      freebsd_instance:
        image: freebsd-14-3-release-amd64-ufs
    - name: FreeBSD 15 amd64 stable
      freebsd_instance:
        image: freebsd-15-0-release-amd64-ufs
    - name: FreeBSD 15 i686 stable
      # Test i686 FreeBSD in 32-bit emulation on a 64-bit host.
      env:
        TARGET: i686-unknown-freebsd
      freebsd_instance:
        image: freebsd-15-0-release-amd64-ufs
  << : *SETUP
  extra_setup_script:
    - . $HOME/.cargo/env
    - cp Cargo.lock.msrv Cargo.lock
    - if [ "$TARGET" = "i686-unknown-freebsd" ]; then rustup target add --toolchain $VERSION i686-unknown-freebsd; fi
  << : *TEST
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  before_cache_script: rm -rf $HOME/.cargo/registry/index 

# Stuff that only needs to be run with nightly Rust
lint_task:
  name: FreeBSD 15 amd64 nightly
  env:
    HOME: /tmp  # cargo cache needs it
    TARGET: x86_64-unknown-freebsd
    VERSION: nightly
  freebsd_instance:
    image: freebsd-15-0-release-amd64-ufs
  << : *SETUP
  extra_setup_script:
    - . $HOME/.cargo/env
    - rustup component add --toolchain $VERSION clippy
    - rustup component add --toolchain $VERSION rustfmt
  cargo_cache:
    folder: $HOME/.cargo/registry
  << : *TEST
  clippy_script:
    - . $HOME/.cargo/env
    - cargo clippy --all-targets -- -D warnings
    - cargo clippy --all-targets --all-features -- -D warnings
  fmt_script:
    - . $HOME/.cargo/env
    - cargo fmt --all -- --check --color=never
  audit_script:
    - . $HOME/.cargo/env
    # install ca_root_nss due to https://github.com/rustsec/rustsec/issues/1137
    - pkg install -y ca_root_nss cargo-audit
    - cargo audit
  minver_script:
    - . $HOME/.cargo/env
    - cargo update -Zdirect-minimal-versions
    - cargo check --all-features --all-targets --all
  before_cache_script: rm -rf $CARGO_HOME/registry/index

# Ensure that the docs can be cross-compiled, as docs.rs does.
task:
  name: Cross docs
  container:
    image: rustlang/rust:nightly
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  env:
    RUSTFLAGS: --cfg docsrs
    RUSTDOCFLAGS: --cfg docsrs
  doc_script:
    - rustup target add x86_64-unknown-freebsd
    - cargo doc --target x86_64-unknown-freebsd --no-deps --all-features
  before_cache_script: rm -rf $HOME/.cargo/registry/index
